fastlane_version "2.66.2"

default_platform :android

platform :android do

    lane :alpha do |options|

        puts "alpha lane building with gradle..."
        puts @project_path
        gradle(task: "clean")
        gradle(
            task: "assemble",
            build_type: "Release",
            project_dir: @project_path
            )

    end
end
